kind: pipeline
type: docker
name: ci

steps:
  - name: format
    image: mansong/drone-terraform:latest
    commands:
      - fmt -write=false -diff=true -check=true

  - name: validate
    image: mansong/drone-terraform:latest
    commands:
       - validate
  
  - name: plan
    image: mansong/drone-terraform:latest
    commands:
      - plan