kind: pipeline
type: docker
name: ci

steps:
  - name: format
    image: hashicorp/terraform:light
    commands:
      - terraform fmt -write=false -diff=true -check=true

  - name: validate
    image: hashicorp/terraform:light
    commands:
       - terraform init 
       - terraform validate
  
  - name: plan
    image: hashicorp/terraform:light
    commands:
      - terraform init
      - terraform plan