apiVersion: v1
kind: Namespace
metadata:
  name: harness-delegate-ng

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: harness-delegate-ng-cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: harness-delegate-ng
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Secret
metadata:
  name: mansong-cogenial-octo-funicular-proxy
  namespace: harness-delegate-ng
type: Opaque
data:
  # Enter base64 encoded username and password, if needed
  PROXY_USER: ""
  PROXY_PASSWORD: ""

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    harness.io/app: harness-delegate
    harness.io/account: sasyuu
    harness.io/name: mansong-cogenial-octo-funicular
  # Name must contain the six letter account identifier: sasyuu
  name: mansong-cogenial-octo-funicular-sasyuu
  namespace: harness-delegate-ng
spec:
  replicas: 8
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      harness.io/app: harness-delegate
      harness.io/account: sasyuu
      harness.io/name: mansong-cogenial-octo-funicular
  serviceName: ""
  template:
    metadata:
      labels:
        harness.io/app: harness-delegate
        harness.io/account: sasyuu
        harness.io/name: mansong-cogenial-octo-funicular
    spec:
      containers:
      - image: harness/delegate:latest
        imagePullPolicy: Always
        name: harness-delegate-instance
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "2560Mi"
          requests:
            cpu: "0.5"
            memory: "2560Mi"
        readinessProbe:
          exec:
            command:
              - test
              - -s
              - delegate.log
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
              - bash
              - -c
              - '[[ -e /opt/harness-delegate/msg/data/watcher-data && $(($(date +%s000) - $(grep heartbeat /opt/harness-delegate/msg/data/watcher-data | cut -d ":" -f 2 | cut -d "," -f 1))) -lt 300000 ]]'
          initialDelaySeconds: 240
          periodSeconds: 10
          failureThreshold: 2
        env:
        - name: ACCOUNT_ID
          value: SAsyUUHTTImuYSZ35HPDvw
        - name: ACCOUNT_SECRET
          value: afaea77d8244014c62d7484f8475f5be
        - name: MANAGER_HOST_AND_PORT
          value: https://app.harness.io
        - name: WATCHER_STORAGE_URL
          value: https://app.harness.io/public/prod/premium/watchers
        - name: WATCHER_CHECK_LOCATION
          value: current.version
        - name: REMOTE_WATCHER_URL_CDN
          value: https://app.harness.io/public/shared/watchers/builds
        - name: DELEGATE_STORAGE_URL
          value: https://app.harness.io
        - name: DELEGATE_CHECK_LOCATION
          value: delegateprod.txt
        - name: DEPLOY_MODE
          value: KUBERNETES
        - name: DELEGATE_NAME
          value: mansong-cogenial-octo-funicular
        - name: DELEGATE_GROUP_ID
          value: Qg1SlTvXQ-OYrcvOwqOZaA
        - name: DELEGATE_DESCRIPTION
          value: ""
        - name: DELEGATE_PROFILE
          value: "kiPMNnvmTKqu-bRZmr2-zw"
        - name: DELEGATE_TYPE
          value: "KUBERNETES"
        - name: DELEGATE_SIZE
          value: "LARGE"
        - name: DELEGATE_SESSION_IDENTIFIER
          value: "ZK582z9DSnKeE3TcyrK_TQ"
        - name: DELEGATE_TASK_LIMIT
          value: "50"
        - name: DELEGATE_ORG_IDENTIFIER
          value: ""
        - name: DELEGATE_PROJECT_IDENTIFIER
          value: ""
        - name: PROXY_HOST
          value: ""
        - name: PROXY_PORT
          value: ""
        - name: PROXY_SCHEME
          value: ""
        - name: NO_PROXY
          value: ""
        - name: PROXY_MANAGER
          value: "true"
        - name: PROXY_USER
          valueFrom:
            secretKeyRef:
              name: mansong-cogenial-octo-funicular-proxy
              key: PROXY_USER
        - name: PROXY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mansong-cogenial-octo-funicular-proxy
              key: PROXY_PASSWORD
        - name: POLL_FOR_TASKS
          value: "false"
        - name: HELM_DESIRED_VERSION
          value: ""
        - name: CF_PLUGIN_HOME
          value: ""
        - name: USE_CDN
          value: "true"
        - name: CDN_URL
          value: https://app.harness.io
        - name: JRE_VERSION
          value: 1.8.0_242
        - name: HELM3_PATH
          value: ""
        - name: HELM_PATH
          value: ""
        - name: CF_CLI6_PATH
          value: ""
        - name: CF_CLI7_PATH
          value: ""
        - name: KUSTOMIZE_PATH
          value: ""
        - name: OC_PATH
          value: ""
        - name: KUBECTL_PATH
          value: ""
        - name: ENABlE_CE
          value: "false"
        - name: GRPC_SERVICE_ENABLED
          value: "true"
        - name: GRPC_SERVICE_CONNECTOR_PORT
          value: "8080"
        - name: CLIENT_TOOLS_DOWNLOAD_DISABLED
          value: "false"
        - name: INSTALL_CLIENT_TOOLS_IN_BACKGROUND
          value: "true"
        - name: DELEGATE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: delegate-service
  namespace: harness-delegate-ng
spec:
  type: ClusterIP
  selector:
    harness.io/app: harness-delegate
    harness.io/account: sasyuu
    harness.io/name: mansong-cogenial-octo-funicular
  ports:
    - port: 8080
